server:
  port: 8081

jwt:
  secret: urieuryeiur

data:
  database:
    users: Users
    relationships: Relationship
    messages: Messages
    channel: ChatChannel
    channelName: ChatChannelName
    inChatChannel: InChatChannel
    constraints: Constraint

  constraints:
    usernameConst: Username
    userEmailConst: UserEmail