server:
  port: 8081

jwt:
  secret: urieuryeiur

data:
  database:
    users: Users
    relationships: Relationship
    constraints: Constraint

  constraints:
    usernameConst: Username
    userEmailConst: UserEmail