server:
  port: 8081

jwt:
  secret: urieuryeiur

data:
  database:
    users: ChatBoxUsers
    relationships: ChatBoxRelationship
    messages: ChatBoxMessages
    channel: ChatBoxChatChannel
    channelName: ChatBoxChatChannelName
    inChatChannel: ChatBoxInChatChannel
    constraints: ChatBoxConstraint

  constraints:
    usernameConst: Username
    userEmailConst: UserEmail

  mongodb:
    database: simplechat
    uri: mongodb://root:password@localhost:27017

    user-collection: users
    relationships: relationships
    messages: messages
    channel: channel
    channelName: ChatChannelName
    inChatChannel: InChatChannel
    constraints: Constraint
